#!/usr/bin/env python3
"""gen_nsf.py — generate a NeatSeq-Flow workflow YAML from a pipeline catalogue.tsv.

Single-authored DAG: the same catalogue that drives run_*_pipeline.sh also produces the
NeatSeq-Flow version, so the two engines cannot drift. Each catalogue step becomes a
Generic module whose script_path invokes the SAME wrapper the bash runner calls; `base:`
edges encode the dependency DAG. Never hand-edit the generated YAML — re-run this.

Usage:
  python3 gen_nsf.py --domain annotation \
      --catalogue annotation/steps/catalogue.tsv \
      --out neatseq_flow/annotation_workflow.yaml
"""
import argparse, os

ROOT = "/mnt/data/Projects/Elad_Chiel/wasp_genome_assembly"

def read_catalogue(path):
    steps = []
    with open(path) as fh:
        for line in fh:
            if line.startswith("#") or not line.strip():
                continue
            f = line.rstrip("\n").split("\t")
            if len(f) < 7:
                continue
            sid, group, mode, env, deps, persample, label = f[:7]
            dep_list = [] if deps.strip() in ("", "-") else [d.strip() for d in deps.split(",") if d.strip()]
            steps.append(dict(id=sid, group=group, mode=mode, env=env,
                              deps=dep_list, per_sample=(persample.strip() == "yes"),
                              label=label))
    return steps

def emit(steps, domain, out):
    L = []
    L.append("# AUTO-GENERATED by annotation/steps/gen_nsf.py — DO NOT EDIT BY HAND.")
    L.append(f"# Regenerate: python3 annotation/steps/gen_nsf.py --domain {domain} ...")
    L.append("# Each step is a Generic module calling the same wrapper the bash runner uses.")
    L.append("Global_params:")
    L.append("    Default_wait: 10")
    L.append("    Executor: Local          # bi-delllinux has no scheduler; flip to SGE on zeus")
    L.append("    conda:")
    L.append("        path: /home/multiomics/miniforge3")
    L.append("        env: NeatSeq_Flow")
    L.append("")
    L.append("Vars:")
    L.append(f"    project_dir: {ROOT}")
    L.append(f"    steps_dir: {ROOT}/{domain}/steps")
    L.append("")
    L.append("Step_params:")
    for s in steps:
        wrapper = f"{ROOT}/{domain}/steps/{s['id']}.sh"
        L.append(f"    {s['id']}:")
        L.append("        module: Generic")
        if s["deps"]:
            L.append("        base: [" + ", ".join(s["deps"]) + "]")
        L.append(f"        script_path: 'bash {wrapper}'")
        L.append(f"        # {s['mode']} | env={s['env']} | {s['label']}")
        L.append("")
    text = "\n".join(L) + "\n"
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as fh:
        fh.write(text)
    print(f"wrote {out} ({len(steps)} steps)")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", required=True)
    ap.add_argument("--catalogue", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    emit(read_catalogue(a.catalogue), a.domain, a.out)

if __name__ == "__main__":
    main()
